name: kojo-stack

services:
  kojo-stack:
    image: docker.jojoaddison.net/kojo-stack:2026.01.3
    hostname: kojo-stack-app
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kojo-stack-app
    ports:
      - "4800:80"
    environment:
      - NODE_ENV=production
      - production=true
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
    networks:
      - kojo-network

networks:
  kojo-network:
    driver: bridge
